new ci

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,77 +1,166 @@
-name: CI/CD
+name: release
 
 on:
   push:
     tags:
-     - '*'
-    branches:
-      - develop
-      - main
-  pull_request:
+      - "[0-9]+.[0-9]+.[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+a[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+b[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
+      - "*"
     branches:
       - "*"
 
+env:
+  PACKAGE_NAME: "py-clock"
+  OWNER: "manojmanivannan"
+
 jobs:
-    pytest_build:
-        runs-on: ubuntu-latest
+  details:
+    runs-on: ubuntu-latest
+    outputs:
+      new_version: ${{ steps.release.outputs.new_version }}
+      suffix: ${{ steps.release.outputs.suffix }}
+      tag_name: ${{ steps.release.outputs.tag_name }}
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Extract tag and Details
+        id: release
+        run: |
+          if [ "${{ github.ref_type }}" = "tag" ]; then
+            TAG_NAME=${GITHUB_REF#refs/tags/}
+            NEW_VERSION=$(echo $TAG_NAME | awk -F'-' '{print $1}')
+            SUFFIX=$(echo $TAG_NAME | grep -oP '[a-z]+[0-9]+' || echo "")
+            echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
+            echo "suffix=$SUFFIX" >> "$GITHUB_OUTPUT"
+            echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
+            echo "Version is $NEW_VERSION"
+            echo "Suffix is $SUFFIX"
+            echo "Tag name is $TAG_NAME"
+          else
+            echo "No tag found"
+            exit 1
+          fi
+  test_cli:
+    needs: [details]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.11"
+
+      - name: Setup Virtual Env
+        shell: bash
+        run: |
+          python -m venv venv
+          source ./venv/bin/activate
+          python -m pip install -r requirements.txt
+
+      - name: Run PyTest 🧪
+        shell: bash
+        run: |
+          source ./venv/bin/activate
+          python -m pytest -v tests
+
+      - name: Test CLI tool 🔧
+        shell: bash
+        run: |
+          source ./venv/bin/activate
+          python setup.py install
+          py-clock -s -m -d
+
+  check_pypi:
+    needs: [details,test_cli]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fetch information from PyPI
+        run: |
+          response=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json || echo "{}")
+          latest_previous_version=$(echo $response | grep -oP '"releases":\{"\K[^"]+' | sort -rV | head -n 1)
+          if [ -z "$latest_previous_version" ]; then
+            echo "Package not found on PyPI."
+            latest_previous_version="0.0.0"
+          fi
+          echo "Latest version on PyPI: $latest_previous_version"
+          echo "latest_previous_version=$latest_previous_version" >> $GITHUB_ENV
+
+      - name: Compare versions and exit if not newer
+        run: |
+          NEW_VERSION=${{ needs.details.outputs.new_version }}
+          LATEST_VERSION=$latest_previous_version
+          if [ "$(printf '%s\n' "$LATEST_VERSION" "$NEW_VERSION" | sort -rV | head -n 1)" != "$NEW_VERSION" ] || [ "$NEW_VERSION" == "$LATEST_VERSION" ]; then
+            echo "The new version $NEW_VERSION is not greater than the latest version $LATEST_VERSION on PyPI."
+            exit 1
+          else
+            echo "The new version $NEW_VERSION is greater than the latest version $LATEST_VERSION on PyPI."
+          fi
+
+
+
+  setup_and_build:
+    needs: [details, check_pypi]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: "3.11"
+
+      - name: Build source and wheel distribution
+        run: |
+          python setup.py sdist bdist_wheel
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: dist
+          path: dist/
+
+  pypi_publish:
+    name: Upload release to PyPI
+    needs: [setup_and_build, details]
+    runs-on: ubuntu-latest
+    environment:
+      name: release
+    permissions:
+      id-token: write
+    steps:
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: dist
+          path: dist/
+
+      - name: Publish distribution to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+
+  github_release:
+    name: Create GitHub Release
+    needs: [setup_and_build, details]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: dist
+          path: dist/
+
+      - name: Create GitHub Release
+        id: create_release
         env:
-          TERM: "linux"
-        steps:
-            - name: Check out the repo
-              uses: actions/checkout@v2
-
-            - name: Set up Python 3.11 🐍
-              uses: actions/setup-python@v3
-              with:
-                python-version: "3.11"
-
-            - name: Setup Virtual Env
-              shell: bash
-              run: |
-                python -m venv venv
-                source ./venv/bin/activate
-                python -m pip install -r requirements.txt
-
-            - name: Run PyTest 🧪
-              shell: bash
-              run: |
-                source ./venv/bin/activate
-                python -m pytest -v tests
-
-            - name: Extract tag name
-              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
-              id: tag
-              run: |
-                echo "TAG_NAME=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
-
-            - name: Set Tag Name
-              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
-              run: |
-                echo "Setting tag name to ${{ env.TAG_NAME }}" && sed -i "s/{{VERSION_PLACEHOLDER}}/${{ env.TAG_NAME }}/g" setup.py
-
-            - name: Test CLI tool 🔧
-              shell: bash
-              run: |
-                source ./venv/bin/activate
-                python setup.py install
-                py-clock -s -m -d
-                
-            - name: Generate distribution 📦
-              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
-              shell: bash
-              run: |
-                source ./venv/bin/activate
-                python -m pip install twine
-                
-                python setup.py sdist bdist_wheel
-
-            - name: Publish Python 🐍 distribution to PyPI
-              if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
-              shell: bash
-              env:
-                TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
-                TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
-              run: |
-                source ./venv/bin/activate
-                twine upload dist/*.whl --skip-existing
-
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          gh release create ${{ needs.details.outputs.tag_name }} dist/* --title ${{ needs.details.outputs.tag_name }} --generate-notes
